# https://hub.docker.com/_/microsoft-dotnet
ARG OS=bionic

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-${OS} AS build
WORKDIR /source

# copy csproj and restore as distinct layers
COPY *.sln .
COPY aspnetapp-3.1/*.csproj ./aspnetapp/
RUN dotnet restore

# copy everything else and build app
COPY aspnetapp-3.1/. ./aspnetapp/
WORKDIR /source/aspnetapp
RUN dotnet publish -c release -o /app --no-restore

# final stage/image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-${OS} AS runtime

WORKDIR /app
COPY --from=build /app ./

# Application Security
RUN mkdir -p /app/TrendAppProtect && \
    mkdir /var/log/appsec
    
COPY TrendAppProtect/ TrendAppProtect/
ENV CORECLR_ENABLE_PROFILING=1
ENV CORECLR_PROFILER={a51743a9-9e05-4a9f-adcd-d39aa322615a}
ENV CORECLR_PROFILER_PATH=/app/TrendAppProtect/bin/libTrendAppProtectProfiler-x64-Linux.so
ENV TREND_AP_CONFIG_FILE=/app/TrendAppProtect/TrendAppProtect.config

ENV ASPNETCORE_ENVIRONMENT="Development"
# /Application Security

EXPOSE 80

ENTRYPOINT ["dotnet", "aspnetapp.dll"]
