# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build

WORKDIR /source

# copy csproj and restore as distinct layers
COPY *.sln .
COPY aspnetapp-3.1/*.csproj ./aspnetapp/
RUN dotnet restore

# copy everything else and build app
COPY aspnetapp-3.1/. ./aspnetapp/
WORKDIR /source/aspnetapp
RUN dotnet publish -c release -o /app --no-restore

# final stage/image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime

WORKDIR /app
COPY --from=build /app ./

# Application Security
RUN mkdir -p /app/trend_app_protect_netcore/bin
COPY bin /app/trend_app_protect_netcore/bin
COPY TrendAppProtect.config /app/trend_app_protect_netcore/

ENV CORECLR_ENABLE_PROFILING=1
ENV CORECLR_PROFILER={a51743a9-9e05-4a9f-adcd-d39aa322615a}
ENV CORECLR_PROFILER_PATH=/app/trend_app_protect_netcore/bin/libTrendAppProtectProfiler-x64-Linux.so
ENV TREND_AP_CONFIG_FILE=/app/trend_app_protect_netcore/TrendAppProtect.config
# /Application Security

ENTRYPOINT ["dotnet", "aspnetapp.dll"]
